workflows:
  android-capacitor-workflow:
    name: Android Capacitor Build (Debug)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "club.hybridx.app"
      java: 17
      node: 20
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js app
        script: |
          npm run build
      - name: Patch Capacitor plugins for Java 17
        script: |
          # Patch capacitor-android
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle
          echo "Patched capacitor-android to use Java 17"

          # Patch capacitor-preferences
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle
          echo "Patched capacitor-preferences to use Java 17"

          # Patch capacitor-status-bar
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/status-bar/android/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/status-bar/android/build.gradle
          echo "Patched capacitor-status-bar to use Java 17"
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Create assets directory
        script: |
          mkdir -p android/app/src/main/assets
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Fix Java version in auto-generated files
        script: |
          # Fix Java version in capacitor-cordova-android-plugins
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle
          echo "Patched capacitor-cordova-android-plugins to use Java 17"
      - name: Set up local.properties and gradle.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "org.gradle.java.home=$JAVA_HOME" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Build Android Debug APK
        script: |
          cd android
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  android-release-workflow:
    name: Android Capacitor Build (Release)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - hybridx_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "club.hybridx.app"
      java: 17
      node: 20
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js app
        script: |
          npm run build
      - name: Patch Capacitor plugins for Java 17
        script: |
          # Patch capacitor-android
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle
          echo "Patched capacitor-android to use Java 17"

          # Patch capacitor-preferences
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle
          echo "Patched capacitor-preferences to use Java 17"

          # Patch capacitor-status-bar
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/status-bar/android/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/status-bar/android/build.gradle
          echo "Patched capacitor-status-bar to use Java 17"
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Create assets directory
        script: |
          mkdir -p android/app/src/main/assets
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Fix Java version in auto-generated files
        script: |
          # Fix Java version in capacitor-cordova-android-plugins
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle
          echo "Patched capacitor-cordova-android-plugins to use Java 17"
      - name: Set up local.properties and gradle.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "org.gradle.java.home=$JAVA_HOME" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Set up keystore environment variables
        script: |
          echo "CM_KEYSTORE_PATH=$CM_KEYSTORE_PATH" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "CM_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "CM_KEY_ALIAS=$CM_KEY_ALIAS" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "CM_KEY_PASSWORD=$CM_KEY_PASSWORD" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Build Android Release AAB
        script: |
          cd android
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew bundleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/native-debug-symbols/**/*.zip
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-release-workflow:
    name: iOS Capacitor Build (Release)
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: hybridx_app_store_connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: club.hybridx.app
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "club.hybridx.app"
        APP_STORE_APP_ID: YOUR_APP_STORE_ID # Replace with your App Store Connect app ID
      xcode: 15.4
      node: 20
      cocoapods: default
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'ios-v*'
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Create assets directory
        script: |
          mkdir -p ios/App/App/public
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set build number
        script: |
          cd ios/App
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
          agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for App Store distribution
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
