workflows:
  android-capacitor-workflow:
    name: Android Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "club.hybridx.app"
      java: 17
      node: 20
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Patch Capacitor plugins for Java 17
        script: |
          # Patch capacitor-android
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle
          echo "Patched capacitor-android to use Java 17"

          # Patch capacitor-preferences
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/preferences/android/build.gradle
          echo "Patched capacitor-preferences to use Java 17"
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Create assets directory
        script: |
          mkdir -p android/app/src/main/assets
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Fix Java version in auto-generated files
        script: |
          # Fix Java version in capacitor-cordova-android-plugins
          sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle 2>/dev/null || \
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/capacitor-cordova-android-plugins/build.gradle
          echo "Patched capacitor-cordova-android-plugins to use Java 17"
      - name: Set up local.properties and gradle.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "org.gradle.java.home=$JAVA_HOME" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Build Android APK
        script: |
          cd android
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
