workflows:
  android-capacitor-workflow:
    name: Android Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "club.hybridx.app"
      node: 20
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Create assets directory
        script: |
          mkdir -p android/app/src/main/assets
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
